In [1]:
from sklearn import datasets, ensemble, metrics, linear_model
import numpy as np

In [11]:
digits = datasets.load_digits()
breast_cancer = datasets.load_breast_cancer()

In [15]:
X_d = digits.data
y_d = digits.target
print(X_d)
print(y_d)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


In [18]:
X_c = breast_cancer.data
y_c = breast_cancer.target
print(X_c[:2, :])
print(y_c[:50])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1]


In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

In [24]:
estimator = BernoulliNB()
result = cross_val_score(estimator, X_d, y=y_d).mean()
result

0.8241736304549674

In [33]:
estimator = MultinomialNB()
result = cross_val_score(estimator, X_d, y=y_d).mean()
result
with open('bayes_2.txt', 'w') as file:
    file.write(str(result))

In [25]:
estimator = GaussianNB()
result = cross_val_score(estimator, X_d, y=y_d).mean()
result

0.8069281956050759

In [28]:
estimator = BernoulliNB()
result = cross_val_score(estimator, X_c, y=y_c).mean()
result

0.6274181027790716

In [31]:
estimator = MultinomialNB()
result = cross_val_score(estimator, X_c, y=y_c).mean()
result


0.8963204471355379

In [32]:
estimator = GaussianNB()
result = cross_val_score(estimator, X_c, y=y_c).mean()
result
with open('bayes_1.txt', 'w') as file:
    file.write(str(result))